-- Add default terms and privacy policy content to forum settings
INSERT INTO public.forum_settings (setting_key, setting_value, setting_type, category, description, is_public) 
VALUES 
(
  'terms_content', 
  '"<h2>1. Acceptance of Terms</h2><p>By accessing and using Minor Hockey Talks, you accept and agree to be bound by the terms and provision of this agreement. These terms apply to all visitors, users, and others who access or use the service.</p><h2>2. Use License</h2><p>Permission is granted to temporarily use Minor Hockey Talks for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:</p><ul><li>modify or copy the materials</li><li>use the materials for any commercial purpose or for any public display</li><li>attempt to reverse engineer any software contained on the website</li><li>remove any copyright or other proprietary notations from the materials</li></ul><h2>3. User Conduct</h2><p>Users agree to use the forum in a respectful manner. Prohibited activities include:</p><ul><li>Posting offensive, abusive, or discriminatory content</li><li>Harassing other users</li><li>Sharing personal information of others without consent</li><li>Spamming or excessive self-promotion</li><li>Posting illegal content or content that violates copyright</li></ul><h2>4. Content Policy</h2><p>All content posted on Minor Hockey Talks must be relevant to minor hockey. We reserve the right to moderate, edit, or remove content that violates our community guidelines or these terms of service.</p><h2>5. Privacy</h2><p>Your privacy is important to us. Please review our Privacy Policy, which also governs your use of the service, to understand our practices.</p><h2>6. Disclaimer</h2><p>The materials on Minor Hockey Talks are provided on an ''as is'' basis. Minor Hockey Talks makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</p><h2>7. Contact Information</h2><p>If you have any questions about these Terms & Conditions, please contact us through our contact form or email us directly.</p>"',
  'text',
  'legal',
  'Terms and Conditions content',
  true
),
(
  'privacy_content', 
  '"<h2>1. Information We Collect</h2><p>Minor Hockey Talks collects information you provide directly to us, such as when you create an account, post content, or contact us for support.</p><ul><li>Account information (username, email address)</li><li>Profile information (bio, avatar)</li><li>Content you post (topics, replies, votes)</li><li>Communication with us (support requests, feedback)</li></ul><h2>2. How We Use Your Information</h2><p>We use the information we collect to:</p><ul><li>Provide, maintain, and improve our services</li><li>Process transactions and send related information</li><li>Send technical notices and support messages</li><li>Respond to your comments and questions</li><li>Monitor and analyze trends, usage, and activities</li><li>Detect, investigate, and prevent fraudulent transactions</li></ul><h2>3. Information Sharing</h2><p>We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except in the following circumstances:</p><ul><li>With your explicit consent</li><li>To comply with legal obligations</li><li>To protect and defend our rights and property</li><li>To prevent or investigate possible wrongdoing</li><li>With service providers who assist in operating our website</li></ul><h2>4. Data Security</h2><p>We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the internet is 100% secure.</p><h2>5. Anonymous Users</h2><p>For users who post anonymously, we collect minimal information:</p><ul><li>Temporary session data for rate limiting</li><li>IP addresses for moderation purposes (accessible only to administrators)</li><li>Generated temporary usernames (no personal identification)</li></ul><h2>6. Your Rights</h2><p>You have the right to:</p><ul><li>Access your personal information</li><li>Correct inaccurate information</li><li>Delete your account and associated data</li><li>Export your data</li><li>Withdraw consent for data processing</li></ul><h2>7. Contact Us</h2><p>If you have any questions about this Privacy Policy, please contact us through our contact form or email us directly.</p>"',
  'text',
  'legal',
  'Privacy Policy content',
  true
)
ON CONFLICT (setting_key) DO NOTHING;